# Generated by Django 4.0.2 on 2022-02-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_news_shop_sizes_news_views_alter_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='shop_sizes',
        ),
    ]
